### ISSUE TITLE
Добавить возможность подписываться на событие blur на элементе мультиселекта

### ISSUE THREAD

**Issue by grushikhin** [tamtakoe/oi.multiselect#3]
Было бы круто, если при потере фокуса внутренним инпутом на элементе вызывалось событие blur.
Сейчас есть функция blurHandler, которая срабатывает при закрытии выпадающего списка с подсказками. Но если подсказок нет, и мы снимаем фокус по клику вне элемента, либо по tab, то эта функция не вызывается.

**Comment by tamtakoe** [comment]
work since 0.1.7
